#!/bin/sh
#
# Simple postinst script for guacd which creates a "guacd" user and group
# and sets the permissions and ownership of /var/run/guacd (the location
# of the guacd.pid file) and /usr/share/guacd (the home directory of the
# guacd user).
#


# Exit on errors
set -e

# User and group names
GUACD_USER="guacd"
GUACD_GROUP="guacd"

# Home directory
GUACD_HOME="/usr/share/guacd"

# Directory which will contain PID files
GUACD_RUN="/var/run/guacd"

# Convenience function for error conditions.
fail() {
    echo "$1" >&2
    exit 1
}

#DEBHELPER#

# Do not exit on errors
set +e

# Create guacd group if it does not exist
groupadd -fr "$GUACD_GROUP" ||\
    fail "Could not create group \"$GUACD_GROUP\""

# Create guacd user if it does not exist
useradd -g "$GUACD_GROUP" -d "$GUACD_HOME" -s /bin/false -r "$GUACD_USER" || (
    [ "$?" != "9" ] && fail "Could not create user \"$GUACD_USER\""
)


exit 0
